language: python
python:
    - "3.5"
before_script:
    - pip install pytest coverage python-coveralls flake8
install: 
    - "python setup.py install"
    - "pip install -r requirements_dev.txt"
script: 
    - coverage run --source checksummit -m py.test 
    - docker build . -t proj 
    - docker run proj python /code/tests/test_checksummit.py 
    - flake8 --exit-zero
after_success:
    - coverage report
    - coveralls
services:
    - docker
